#!/usr/bin/env python3
"""Extract WEB_PAGE string from web_page.h, gzip it, output a C array.

Usage: python compress_web_page.py main/infrastructure/driving/web_page.h web_page_gz.cpp
"""

import re
import gzip
import sys


def decode_c_escapes(s: str) -> str:
    """Decode C/C++ escape sequences including \\uXXXX and \\UXXXXXXXX."""
    # Handle \\UXXXXXXXX first (32-bit, non-BMP) — must be before \\uXXXX
    def unescape_unicode32(m):
        return chr(int(m.group(1), 16))
    s = re.sub(r'\\U([0-9a-fA-F]{8})', unescape_unicode32, s)

    # Handle \\uXXXX (16-bit, BMP)
    def unescape_unicode16(m):
        return chr(int(m.group(1), 16))
    s = re.sub(r'\\u([0-9a-fA-F]{4})', unescape_unicode16, s)

    # Handle standard C escapes (order matters)
    s = (s
         .replace('\\\\', '\\')
         .replace('\\"', '"')
         .replace('\\n', '\n')
         .replace('\\t', '\t')
         .replace('\\r', '\r'))
    return s


def extract_c_string_literals(source: str) -> str:
    """Extract and decode concatenated C string literals after WEB_PAGE[] =."""
    m = re.search(r'WEB_PAGE\[\]\s*=\s*', source)
    if not m:
        raise SystemExit("WEB_PAGE[] = not found in source")
    rest = source[m.end():]

    decoded = []
    for m in re.finditer(r'"((?:[^"\\]|\\.)*)"', rest):
        raw = m.group(1)
        decoded.append(decode_c_escapes(raw))
        # Stop after the string that is followed by optional whitespace and ;
        tail = rest[m.end():]
        if re.match(r'\s*;', tail):
            break
    return ''.join(decoded)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} web_page.h web_page_gz.inc")
        sys.exit(1)

    src_path, out_path = sys.argv[1], sys.argv[2]

    with open(src_path, 'r', encoding='utf-8') as f:
        source = f.read()

    html = extract_c_string_literals(source).encode('utf-8')
    print(f"Extracted HTML: {len(html)} bytes")

    compressed = gzip.compress(html, compresslevel=9)
    print(f"Gzipped: {len(compressed)} bytes ({len(compressed)*100//len(html)}%)")

    # Generate C include file (to be #included directly, so same translation unit)
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by compress_web_page.py — do not edit\n')
        f.write(f'// Original: {len(html)} bytes, gzipped: {len(compressed)} bytes\n')
        f.write(f'static const uint32_t WEB_PAGE_GZ_LEN = {len(compressed)};\n')
        f.write(f'static const uint8_t WEB_PAGE_GZ[] = {{\n')
        for i, b in enumerate(compressed):
            if i % 16 == 0:
                f.write('   ')
            f.write(f' 0x{b:02x},')
            if i % 16 == 15:
                f.write('\n')
        if len(compressed) % 16 != 0:
            f.write('\n')
        f.write('};\n')

    print(f"Written {out_path}")


if __name__ == '__main__':
    main()
