idf_component_register(
    SRCS
        "main.cpp"
        "endpoints/opentherm/opentherm.c"
        "endpoints/sensors/sensors.c"
        "model/model.cpp"
        "controller/controller.cpp"
        "endpoints/endpoints.cpp"
        "endpoints/opentherm/opentherm_endpoint.cpp"
        "endpoints/webserver/webserver_endpoint.cpp"
        "endpoints/sensors/sensors_endpoint.cpp"
        "endpoints/sntp/sntp_endpoint.cpp"
        "endpoints/wifi/wifi_endpoint.cpp"
        "log/log_service.cpp"
        "stats/stats_service.cpp"
    INCLUDE_DIRS
        "."
        "interfaces"
        "model"
        "controller"
        "log"
        "stats"
        "endpoints/opentherm"
        "endpoints/webserver"
        "endpoints/sensors"
        "endpoints/sntp"
        "endpoints/wifi"
    REQUIRES
        esp_wifi
        esp_http_server
        nvs_flash
        esp_netif
        driver
        esp_timer
        esp_event
        log
)