#pragma once

/* Встроенная HTML-страница. Хранится в Flash (RODATA).
   IP адрес определяется динамически через window.location.hostname. */

static const char WEB_PAGE[] =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Baxi duo-tec compact</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:Arial,sans-serif;background:#1a1a2e;color:#eee;min-height:100vh}"
".header{background:#16213e;padding:16px 24px;border-bottom:2px solid #0f3460}"
".header h1{font-size:1.3em;color:#e94560}"
".header .sub{font-size:.8em;color:#aaa;margin-top:2px}"
".container{max-width:900px;margin:0 auto;padding:16px}"
".grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:16px}"
"@media(max-width:600px){"
".grid{grid-template-columns:repeat(3,1fr)}"
".ctrl-row{flex-direction:column;align-items:stretch;gap:8px}"
".ctrl-row label{flex:none}"
".header{padding:12px 16px}"
".container{padding:10px}"
".card{padding:10px}"
".card .value{font-size:1.4em}"
"}"
".card{background:#16213e;border-radius:8px;padding:16px;border:1px solid #0f3460}"
".card h3{font-size:.8em;color:#aaa;text-transform:uppercase;margin-bottom:8px}"
".card .value{font-size:1.8em;font-weight:bold;color:#4fc3f7}"
".card .unit{font-size:.8em;color:#aaa;margin-left:4px}"
".status-row{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}"
".badge{padding:6px 14px;border-radius:20px;font-size:.85em;font-weight:bold}"
".badge.on{background:#1b5e20;color:#a5d6a7;border:1px solid #388e3c}"
".badge.off{background:#37474f;color:#90a4ae;border:1px solid #546e7a}"
".badge.warn{background:#e65100;color:#ffcc80;border:1px solid #f57c00}"
".section{background:#16213e;border-radius:8px;padding:12px;margin-bottom:10px;border:1px solid #0f3460}"
".section h2{font-size:.95em;color:#4fc3f7;margin-bottom:8px;padding-bottom:6px;border-bottom:1px solid #0f3460}"
".ctrl-row{display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap}"
".ctrl-row label{flex:0 0 140px;font-size:.85em;color:#ccc}"
".ctrl-row input[type=range]{flex:1;min-width:120px;accent-color:#e94560}"
".temp-display{width:70px;text-align:center;font-size:1.1em;font-weight:bold;color:#4fc3f7}"
".toggle{position:relative;display:inline-block;width:62px;height:32px}"
".toggle input{opacity:0;position:absolute;width:0;height:0}"
".slider{display:block;width:62px;height:32px;background:#546e7a;"
"border-radius:16px;cursor:pointer;transition:background .3s;"
"box-shadow:inset 0 0 0 2px rgba(0,0,0,.25),inset 0 2px 4px rgba(0,0,0,.3);"
"position:relative}"
".slider:before{content:'';position:absolute;width:26px;height:26px;"
"top:3px;left:3px;background:#fff;border-radius:50%;"
"box-shadow:0 2px 5px rgba(0,0,0,.45);"
"transition:left .25s ease}"
"input:checked+.slider{background:#e94560}"
"input:checked+.slider:before{left:calc(100% - 29px)}"
".btn{padding:10px 28px;background:#e94560;color:#fff;border:none;border-radius:6px;"
"cursor:pointer;font-size:.95em;font-weight:bold;transition:.2s}"
".btn:hover{background:#c62828}"
".btn:active{transform:scale(.97)}"
".pm{width:40px;height:40px;border:1px solid #0f3460;background:#16213e;color:#4fc3f7;"
"font-size:1.4em;border-radius:8px;cursor:pointer;flex-shrink:0;line-height:1}"
".pm:active{background:#0f3460}"
".info-row{display:flex;justify-content:space-between;align-items:center;"
"padding:5px 0;border-bottom:1px solid #0f3460;font-size:.85em}"
".info-row:last-child{border-bottom:none}"
".info-label{color:#aaa}"
".info-val{color:#eee;font-weight:bold}"
".sh{text-align:center;padding:6px 2px;border-radius:4px;cursor:pointer;"
"font-size:.7em;line-height:1.3;user-select:none;border:2px solid #0f3460;background:#1a1a2e}"
".sh .ht{color:#aaa;font-size:.85em}"
".sh .tt{font-weight:bold;color:#4fc3f7}"
".sh.sel{border-color:#e94560}"
".sh.now{background:#0f3460}"
".pipe{stroke:#37474f;stroke-width:4;fill:none;stroke-linecap:round;stroke-linejoin:round}"
".pipe.hot{stroke:#e53935}"
".pipe.cold{stroke:#42a5f5}"
".pipe.flow{stroke-dasharray:8 6;animation:pflow .5s linear infinite}"
".pipe.idle{stroke-dasharray:12 4;animation:pidle 2s ease-in-out infinite}"
"@keyframes pflow{to{stroke-dashoffset:-14}}"
"@keyframes pidle{0%,100%{stroke-opacity:.3}50%{stroke-opacity:1}}"
".boxa{fill:#1a1a2e;stroke:#37474f;stroke-width:2}"
".boxa.on{stroke:#4fc3f7}"
".boxa.fl{stroke:#ff9800;fill:#1a1a2e;animation:flglow 1s ease-in-out infinite alternate}"
"@keyframes flglow{from{stroke:#ff9800}to{stroke:#e65100}}"
".flame-icon{transform-box:fill-box;transform-origin:center bottom}"
".flame-icon.on{animation:flwave .4s ease-in-out infinite alternate}"
"@keyframes flwave{from{transform:scaleY(1) scaleX(1)}to{transform:scaleY(1.2) scaleX(.85)}}"
".pump-txt.on{fill:#4fc3f7;animation:pspin 1s linear infinite;transform-box:fill-box;transform-origin:center}"
"@keyframes pspin{to{transform:rotate(360deg)}}"
"</style>"
"</head>"
"<body>"
"<div class='header'>"
"<h1>Baxi duo-tec compact &mdash; Управление</h1>"
"<div class='sub'>OpenTherm Gateway | ESP32 | WiFi</div>"
"</div>"
"<div class='container'>"
"<div class='section' style='margin-top:12px'>"
"<div style='display:flex;justify-content:space-between;align-items:center'>"
"<h2 style='margin:0;border:none;padding:0'>Статус котла</h2>"
"<span id='conn_badge' class='badge off'>Нет связи</span>"
"</div>"
"<div class='status-row' style='margin-top:12px'>"
"<span id='b_flame' class='badge off'>Горелка</span>"
"<span id='b_ch'    class='badge off'>Отопление</span>"
"<span id='b_dhw'   class='badge off'>Бойлер КН</span>"
"<span id='b_fault' class='badge off'>Авария</span>"
"<button id='btn_reset' class='btn' style='background:#c62828;font-size:.75em;padding:4px 10px;display:none;margin-left:8px' onclick='resetFault()'>Сброс</button>"
"</div>"
"</div>"
"<div class='section'>"
"<h2>Схема котла</h2>"
"<div style='overflow-x:auto'>"
"<svg viewBox='0 0 650 240' xmlns='http://www.w3.org/2000/svg' style='width:100%;min-width:500px;display:block;margin:0 auto'>"
"<path id='pfl' class='pipe' d='M95,85 H125'/>"
"<path id='ps1' class='pipe' d='M225,85 H288'/>"
"<path id='pcf' class='pipe' d='M310,65 V37 H430'/>"
"<path id='pdf' class='pipe' d='M310,105 V170 H430'/>"
"<path id='pcm' class='pipe' d='M530,37 H600 V208'/>"
"<path id='pdm' class='pipe' d='M530,170 H600 V208'/>"
"<path id='prt' class='pipe' d='M600,208 H272'/>"
"<path id='prp' class='pipe' d='M228,208 H175 V125'/>"
"<rect id='box_brn' class='boxa' x='10' y='55' width='85' height='60' rx='6'/>"
"<text x='52' y='72' text-anchor='middle' font-size='12' fill='#aaa'>\u0413\u043e\u0440\u0435\u043b\u043a\u0430</text>"
"<text x='52' y='90' text-anchor='middle' font-size='18' id='t_fire' class='flame-icon'>\U0001F525</text>"
"<text x='52' y='108' text-anchor='middle' font-size='13' font-weight='bold' fill='#4fc3f7' id='t_mod'>--%</text>"
"<rect id='box_hx' class='boxa' x='125' y='45' width='100' height='80' rx='6'/>"
"<text x='175' y='66' text-anchor='middle' font-size='10' fill='#888'>\u0422\u0435\u043f\u043b\u043e-</text>"
"<text x='175' y='78' text-anchor='middle' font-size='10' fill='#888'>\u043e\u0431\u043c\u0435\u043d\u043d\u0438\u043a</text>"
"<text x='175' y='96' text-anchor='middle' font-size='13' fill='#ef6c00' id='t_ft'>\u25b2 --\u00b0C</text>"
"<text x='175' y='114' text-anchor='middle' font-size='13' fill='#42a5f5' id='t_rt'>\u25bc --\u00b0C</text>"
"<polygon id='box_vlv' class='boxa' points='288,85 310,63 332,85 310,107'/>"
"<text x='310' y='90' text-anchor='middle' font-size='11' fill='#aaa' id='t_vlv'>\u21d4</text>"
"<rect id='box_ch' class='boxa' x='430' y='10' width='100' height='55' rx='6'/>"
"<text x='480' y='43' text-anchor='middle' font-size='13' fill='#aaa'>\u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u0435</text>"
"<rect id='box_dhw' class='boxa' x='430' y='142' width='100' height='55' rx='6'/>"
"<text x='480' y='164' text-anchor='middle' font-size='13' fill='#aaa'>\u0411\u043e\u0439\u043b\u0435\u0440 \u041a\u041d</text>"
"<text x='480' y='184' text-anchor='middle' font-size='14' fill='#4fc3f7' id='t_dht'>--\u00b0C</text>"
"<circle id='box_pump' class='boxa' cx='250' cy='208' r='22'/>"
"<text x='250' y='204' text-anchor='middle' font-size='20' fill='#aaa' id='t_pump' class='pump-txt'>\u21bb</text>"
"<text x='250' y='218' text-anchor='middle' font-size='9' fill='#aaa'>\u041d\u0430\u0441\u043e\u0441</text>"
"<text x='430' y='225' text-anchor='middle' font-size='11' fill='#555'>\u043e\u0431\u0440\u0430\u0442\u043a\u0430</text>"
"</svg>"
"</div>"
"</div>"
"<div class='grid'>"
"<div class='card'><h3>Подача CH</h3>"
"<span class='value' id='ch_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"<div class='card'><h3>Обратка CH</h3>"
"<span class='value' id='ret_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"<div class='card'><h3>Бойлер КН</h3>"
"<span class='value' id='dhw_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"<div class='card'><h3>Модуляция</h3>"
"<span class='value' id='modulation'>--</span><span class='unit'>%</span></div>"
"<div class='card'><h3>3-ход. клапан</h3>"
"<span class='value' style='font-size:1.1em' id='valve_state'>--</span></div>"
"</div>"
"<div class='section'>"
"<h2>Управление</h2>"
"<div class='ctrl-row'>"
"<label>Отопление (CH)</label>"
"<label class='toggle'><input type='checkbox' id='ch_en' onchange='setDirty()'>"
"<span class='slider'></span></label>"
"<span id='ch_en_lbl' style='font-size:.85em;color:#aaa'>Выкл</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Уставка CH</label>"
"<button class='pm' onclick='adj(\"ch_sp\",-1)'>−</button>"
"<input type='range' id='ch_sp' min='20' max='80' step='1' value='60' "
"oninput='updateLabel(\"ch_sp_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"ch_sp\",1)'>+</button>"
"<span class='temp-display'><span id='ch_sp_v'>60</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Нагрев бойлера КН</label>"
"<label class='toggle'><input type='checkbox' id='dhw_en' onchange='setDirty()'>"
"<span class='slider'></span></label>"
"<span id='dhw_en_lbl' style='font-size:.85em;color:#aaa'>Выкл</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Уставка бойлера КН</label>"
"<button class='pm' onclick='adj(\"dhw_sp\",-1)'>−</button>"
"<input type='range' id='dhw_sp' min='40' max='80' step='1' value='60' "
"oninput='updateLabel(\"dhw_sp_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"dhw_sp\",1)'>+</button>"
"<span class='temp-display'><span id='dhw_sp_v'>60</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<button class='btn' onclick='applyControl()'>Применить</button>"
"<span id='apply_msg' style='font-size:.85em;color:#4caf50;margin-left:8px'></span>"
"</div>"
"</div>"
"<div class='section'>"
"<h2 style='display:flex;align-items:center;gap:12px'>Расписание отопления"
"<label class='toggle'><input type='checkbox' id='sched_en' onchange='schedDirty=true'>"
"<span class='slider'></span></label>"
"<span id='sched_status' style='font-size:.75em;color:#aaa'></span></h2>"
"<div id='sched_grid' style='display:grid;grid-template-columns:repeat(12,1fr);gap:3px;margin:8px 0'></div>"
"<div class='ctrl-row' style='margin-top:8px'>"
"<label>Температура</label>"
"<button class='pm' onclick='adj(\"sched_t\",-1)'>−</button>"
"<input type='range' id='sched_t' min='20' max='80' step='1' value='30' "
"oninput='updateLabel(\"sched_tv\",this.value)'>"
"<button class='pm' onclick='adj(\"sched_t\",1)'>+</button>"
"<span class='temp-display'><span id='sched_tv'>30</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<button class='btn' style='font-size:.85em;padding:8px 16px' onclick='schedSet()'>Установить</button>"
"<button class='btn' style='font-size:.85em;padding:8px 16px' onclick='schedSelectAll()'>Выбрать все</button>"
"<button class='btn' style='font-size:.85em;padding:8px 16px;background:#546e7a' onclick='schedClear()'>Снять</button>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<button class='btn' onclick='schedSave()'>Сохранить</button>"
"<span id='sched_msg' style='font-size:.85em;color:#4caf50;margin-left:8px'></span>"
"</div>"
"</div>"
"<div class='section'>"
"<h2>Диагностика</h2>"
"<div class='info-row'><span class='info-label'>Код ошибки (OEM)</span>"
"<span class='info-val' id='oem_fault'>--</span></div>"
"<div class='info-row'><span class='info-label'>Флаги ошибок (ASF)</span>"
"<span class='info-val' id='asf_flags'>--</span></div>"
"<div class='info-row'><span class='info-label'>OEM диагностика</span>"
"<span class='info-val' id='oem_diag'>--</span></div>"
"<div class='info-row'><span class='info-label'>Уставка CH (границы)</span>"
"<span class='info-val' id='ch_bounds'>--</span></div>"
"<div class='info-row'><span class='info-label'>Уставка DHW (границы)</span>"
"<span class='info-val' id='dhw_bounds'>--</span></div>"
"</div>"
"<div class='section'>"
"<h2>Информация об устройстве</h2>"
"<div class='info-row'><span class='info-label'>IP адрес</span>"
"<span class='info-val' id='device_ip'>...</span></div>"
"<div class='info-row'><span class='info-label'>Версия ПО котла</span>"
"<span class='info-val' id='slave_ver'>--</span></div>"
"<div class='info-row'><span class='info-label'>Версия OT</span>"
"<span class='info-val' id='ot_ver'>--</span></div>"
"<div class='info-row'><span class='info-label'>Платформа</span>"
"<span class='info-val'>ESP32 + WiFi</span></div>"
"<div class='info-row'><span class='info-label'>Часовой пояс</span>"
"<span class='info-val' style='display:flex;align-items:center;gap:6px'>"
"UTC+<input type='number' id='tz_val' value='3' min='-12' max='14' "
"style='width:50px;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;"
"border-radius:4px;padding:4px;font-size:.9em;text-align:center'>"
"<button class='btn' style='padding:4px 12px;font-size:.75em' onclick='setTz()'>OK</button>"
"<span id='tz_msg' style='font-size:.8em;color:#4caf50'></span>"
"</span></div>"
"<div class='info-row'><span class='info-label'>Время ESP32</span>"
"<span class='info-val' id='esp_time'>--:--:--</span></div>"
"<div class='info-row'><span class='info-label'>Обновление данных</span>"
"<span class='info-val'>каждые 2 сек</span></div>"
"</div>"
"<div style='text-align:center;margin:20px 0 8px'>"
"<button class='btn' style='background:#c62828' onclick='shutdownBoiler()'>Выключить котёл</button>"
"<span id='shutdown_msg' style='font-size:.85em;margin-left:8px'></span>"
"</div>"
"</div>"
"<script>"
"var dirty=false;"
"document.getElementById('device_ip').textContent=window.location.hostname;"
"function fmt1(v){return isNaN(v)?'--.-':parseFloat(v).toFixed(1);}"
"function fmt0(v){return isNaN(v)?'--':Math.round(v);}"
"function badge(id,on,onTxt,offTxt,warn){"
"var el=document.getElementById(id);"
"el.className='badge '+(warn?'warn':(on?'on':'off'));"
"el.textContent=on?onTxt:offTxt;}"
"function updateLabel(id,v){document.getElementById(id).textContent=v;}"
"function adj(id,d){var s=document.getElementById(id);var v=parseInt(s.value)+d;"
"v=Math.max(parseInt(s.min),Math.min(parseInt(s.max),v));"
"s.value=v;updateLabel(id+'_v',v);setDirty();}"
"function setTz(){"
"var v=parseInt(document.getElementById('tz_val').value);"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({tz_offset:v})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('tz_msg');"
"m.textContent=d.ok?'OK':'Err';"
"setTimeout(function(){m.textContent='';},2000);"
"})['catch'](function(){});}"
"function setDirty(){"
"dirty=true;"
"document.getElementById('ch_en_lbl').textContent=document.getElementById('ch_en').checked?'Вкл':'Выкл';"
"document.getElementById('dhw_en_lbl').textContent=document.getElementById('dhw_en').checked?'Вкл':'Выкл';}"
"function applyControl(){"
"var data={"
"ch_enable:document.getElementById('ch_en').checked?1:0,"
"dhw_enable:document.getElementById('dhw_en').checked?1:0,"
"ch_setpoint:parseInt(document.getElementById('ch_sp').value),"
"dhw_setpoint:parseInt(document.getElementById('dhw_sp').value)};"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(data)})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('apply_msg');"
"m.textContent=d.ok?'Применено':'Ошибка';"
"m.style.color=d.ok?'#4caf50':'#f44336';"
"dirty=false;"
"setTimeout(function(){m.textContent='';},3000);"
"})['catch'](function(){"
"document.getElementById('apply_msg').textContent='Ошибка связи';});}"
"function shutdownBoiler(){"
"if(!confirm('Выключить котёл? После этого можно отключать ESP32.'))return;"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ch_enable:0,dhw_enable:0})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('shutdown_msg');"
"m.textContent=d.ok?'Котёл выключен':'Ошибка';"
"m.style.color=d.ok?'#4caf50':'#f44336';"
"dirty=false;"
"})['catch'](function(){"
"document.getElementById('shutdown_msg').textContent='Ошибка связи';});}"
"function resetFault(){"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({fault_reset:1})})"
".then(function(r){return r.json();})"
".then(function(){})['catch'](function(){});}"
"function setP(id,on,a){var e=document.getElementById(id);if(e)e.setAttribute('class','pipe'+(on?(a||''):''));}"
"function poll(){"
"fetch('/api/status')"
".then(function(r){return r.json();})"
".then(function(d){"
"badge('conn_badge',d.connected,'Подключено','Нет связи',false);"
"badge('b_flame',d.flame,'Горелка ON','Горелка OFF',false);"
"badge('b_ch',d.ch_active,'CH работает','CH стоп',false);"
"badge('b_dhw',d.dhw_active,'Бойлер нагрев','Бойлер стоп',false);"
"badge('b_fault',d.fault,'АВАРИЯ','Авария нет',d.fault);"
"document.getElementById('btn_reset').style.display=d.fault?'inline-block':'none';"
"document.getElementById('ch_temp').textContent=fmt1(d.ch_temp);"
"document.getElementById('ret_temp').textContent=fmt1(d.return_temp);"
"document.getElementById('dhw_temp').textContent=fmt1(d.dhw_temp);"
"document.getElementById('modulation').textContent=fmt0(d.modulation);"
/* 3-ход. клапан: определяем положение из флага dhw_active */
"var vs=document.getElementById('valve_state');"
"vs.textContent=d.dhw_active?'\u2192 Бойлер':'\u2192 Отопление';"
"vs.style.color=d.dhw_active?'#4fc3f7':'#a5d6a7';"
/* Обновить границы слайдера бойлера из ответа котла (ID=48) */
"if(d.dhw_sp_max>d.dhw_sp_min&&d.dhw_sp_max>0){"
"var sl=document.getElementById('dhw_sp');"
"sl.min=d.dhw_sp_min;sl.max=d.dhw_sp_max;}"
"if(d.ch_sp_max>d.ch_sp_min&&d.ch_sp_max>0){"
"var cs=document.getElementById('ch_sp');"
"cs.min=d.ch_sp_min;cs.max=d.ch_sp_max;}"
"if(!dirty){"
"document.getElementById('ch_en').checked=!!d.ch_enable;"
"document.getElementById('dhw_en').checked=!!d.dhw_enable;"
"document.getElementById('ch_sp').value=d.ch_setpoint;"
"document.getElementById('ch_sp_v').textContent=Math.round(d.ch_setpoint);"
"document.getElementById('dhw_sp').value=d.dhw_setpoint;"
"document.getElementById('dhw_sp_v').textContent=Math.round(d.dhw_setpoint);"
"document.getElementById('ch_en_lbl').textContent=d.ch_enable?'Вкл':'Выкл';"
"document.getElementById('dhw_en_lbl').textContent=d.dhw_enable?'Вкл':'Выкл';}"
"if(d.time)document.getElementById('esp_time').textContent=d.time;"
"document.getElementById('oem_fault').textContent=d.oem_fault||'0';"
"document.getElementById('asf_flags').textContent='0x'+('0'+d.asf_flags.toString(16)).slice(-2);"
"document.getElementById('oem_diag').textContent=d.oem_diag||'0';"
"document.getElementById('ch_bounds').textContent=d.ch_sp_min+' .. '+d.ch_sp_max+' \\u00b0C';"
"document.getElementById('dhw_bounds').textContent=d.dhw_sp_min+' .. '+d.dhw_sp_max+' \\u00b0C';"
"document.getElementById('slave_ver').textContent='Type '+d.slave_type+', v'+d.slave_ver;"
"document.getElementById('ot_ver').textContent=d.ot_ver>0?d.ot_ver.toFixed(1):'N/A';"
"if(d.tz_offset!=null)document.getElementById('tz_val').value=d.tz_offset;"
"var fl=d.flame,pw=d.ch_active||d.dhw_active,dh=d.dhw_active;"
"var chA=pw&&!dh,dhA=pw&&dh,af=pw?' flow':(fl?' idle':'');"
"setP('pfl',fl,fl?(pw?' flow':' idle'):'');"
"setP('ps1',pw||fl,' hot'+af);"
"setP('pcf',chA,' hot'+(chA?' flow':''));setP('pdf',dhA,' hot'+(dhA?' flow':''));"
"setP('pcm',chA,' cold'+(chA?' flow':''));setP('pdm',dhA,' cold'+(dhA?' flow':''));"
"var rt=chA||dhA;setP('prt',rt,' cold'+(rt?' flow':''));setP('prp',rt,' cold'+(rt?' flow':''));"
"document.getElementById('box_brn').setAttribute('class','boxa'+(fl?' fl':''));"
"document.getElementById('t_fire').setAttribute('class','flame-icon'+(fl?' on':''));"
"document.getElementById('box_hx').setAttribute('class','boxa'+(pw?' on':''));"
"document.getElementById('box_pump').setAttribute('class','boxa'+(pw?' on':''));"
"document.getElementById('t_pump').setAttribute('class','pump-txt'+(pw?' on':''));"
"document.getElementById('box_vlv').setAttribute('class','boxa'+(pw?' on':''));"
"document.getElementById('box_ch').setAttribute('class','boxa'+(chA?' on':''));"
"document.getElementById('box_dhw').setAttribute('class','boxa'+(dhA?' on':''));"
"document.getElementById('t_mod').textContent=fl?fmt0(d.modulation)+'%':'--';"
"document.getElementById('t_ft').textContent='\\u25b2 '+fmt1(d.ch_temp)+'\\u00b0';"
"document.getElementById('t_rt').textContent='\\u25bc '+fmt1(d.return_temp)+'\\u00b0';"
"document.getElementById('t_dht').textContent=fmt1(d.dhw_temp)+'\\u00b0';"
"document.getElementById('t_vlv').textContent=pw?(dh?'\\u2192 \\u0411\\u041a\\u041d':'\\u2192 CH'):'\\u21d4';"
"})['catch'](function(){badge('conn_badge',false,'','Нет связи',false);});}"
/* Расписание */
"var sTemps=[];"
"var sSel=[];"
"var schedDirty=false;"
"var schedLoaded=false;"
"function schedInit(){"
"var g=document.getElementById('sched_grid');"
"g.innerHTML='';"
"for(var i=0;i<24;i++){"
"var d=document.createElement('div');"
"d.className='sh';d.id='sh'+i;"
"d.innerHTML='<div class=\"ht\">'+String(i).padStart(2,'0')+'</div><div class=\"tt\" id=\"st'+i+'\">--</div>';"
"d.onclick=(function(idx){return function(){sSel[idx]=!sSel[idx];schedRender();};})(i);"
"g.appendChild(d);}"
"}"
"function schedRender(){"
"for(var i=0;i<24;i++){"
"var el=document.getElementById('sh'+i);"
"var cls='sh';"
"if(sSel[i])cls+=' sel';"
"el.className=cls;"
"document.getElementById('st'+i).textContent=sTemps[i]!=null?Math.round(sTemps[i]):'--';}}"
"function schedSet(){"
"var t=parseInt(document.getElementById('sched_t').value);"
"for(var i=0;i<24;i++){if(sSel[i])sTemps[i]=t;}"
"schedDirty=true;schedRender();}"
"function schedSelectAll(){for(var i=0;i<24;i++)sSel[i]=true;schedRender();}"
"function schedClear(){for(var i=0;i<24;i++)sSel[i]=false;schedRender();}"
"function schedSave(){"
"var data={enabled:document.getElementById('sched_en').checked?1:0,temps:sTemps};"
"fetch('/api/schedule',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(data)})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('sched_msg');"
"m.textContent=d.ok?'Сохранено':'Ошибка';"
"m.style.color=d.ok?'#4caf50':'#f44336';"
"schedDirty=false;"
"setTimeout(function(){m.textContent='';},3000);"
"})['catch'](function(){"
"document.getElementById('sched_msg').textContent='Ошибка связи';});}"
"function schedPoll(){"
"fetch('/api/schedule')"
".then(function(r){return r.json();})"
".then(function(d){"
"if(!schedDirty){"
"sTemps=d.temps.slice();"
"document.getElementById('sched_en').checked=!!d.enabled;schedRender();}"
"var h=d.hour;"
"for(var i=0;i<24;i++){var el=document.getElementById('sh'+i);"
"if(h==i)el.classList.add('now');else el.classList.remove('now');}"
"var st=document.getElementById('sched_status');"
"st.textContent=d.enabled?(h>=0?'Час: '+h+':00, уставка: '+Math.round(d.temps[h])+'\\u00b0C':'NTP...'):'Выкл';"
"})['catch'](function(){});}"
"for(var i=0;i<24;i++){sTemps.push(30);sSel.push(false);}"
"schedInit();schedPoll();setInterval(schedPoll,5000);"
"poll();"
"setInterval(poll,2000);"
"</script>"
"</body></html>";
