#pragma once

/* Встроенная HTML-страница. Хранится в Flash (RODATA).
   IP адрес определяется динамически через window.location.hostname. */

static const char WEB_PAGE[] =
"<!DOCTYPE html>"
"<html lang='ru'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Baxi duo-tec compact</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:Arial,sans-serif;background:#1a1a2e;color:#eee;min-height:100vh}"
".header{background:#16213e;padding:16px 24px;border-bottom:2px solid #0f3460}"
".header h1{font-size:1.3em;color:#e94560}"
".header .sub{font-size:.8em;color:#aaa;margin-top:2px}"
".container{max-width:900px;margin:0 auto;padding:16px}"
".grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:16px}"
"@media(max-width:600px){"
".grid{grid-template-columns:repeat(3,1fr)}"
".ctrl-row{flex-direction:column;align-items:stretch;gap:8px}"
".ctrl-row label{flex:none}"
".header{padding:12px 16px}"
".container{padding:10px}"
".card{padding:10px}"
".card .value{font-size:1.4em}"
"}"
".card{background:#16213e;border-radius:8px;padding:16px;border:1px solid #0f3460}"
".card h3{font-size:.8em;color:#aaa;text-transform:uppercase;margin-bottom:8px}"
".card .value{font-size:1.8em;font-weight:bold;color:#4fc3f7}"
".card .unit{font-size:.8em;color:#aaa;margin-left:4px}"
".status-row{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}"
".badge{padding:6px 14px;border-radius:20px;font-size:.85em;font-weight:bold}"
".badge.on{background:#1b5e20;color:#a5d6a7;border:1px solid #388e3c}"
".badge.off{background:#37474f;color:#90a4ae;border:1px solid #546e7a}"
".badge.warn{background:#e65100;color:#ffcc80;border:1px solid #f57c00}"
".section{background:#16213e;border-radius:8px;padding:12px;margin-bottom:10px;border:1px solid #0f3460}"
".section h2{font-size:.95em;color:#4fc3f7;margin-bottom:8px;padding-bottom:6px;border-bottom:1px solid #0f3460}"
".ctrl-row{display:flex;align-items:center;gap:8px;margin-bottom:8px;flex-wrap:wrap}"
".ctrl-row label{flex:0 0 140px;font-size:.85em;color:#ccc}"
".ctrl-row input[type=range]{flex:1;min-width:120px;accent-color:#e94560}"
".temp-display{width:70px;text-align:center;font-size:1.1em;font-weight:bold;color:#4fc3f7}"
".toggle{position:relative;display:inline-block;width:62px;height:32px}"
".toggle input{opacity:0;position:absolute;width:0;height:0}"
".slider{display:block;width:62px;height:32px;background:#546e7a;"
"border-radius:16px;cursor:pointer;transition:background .3s;"
"box-shadow:inset 0 0 0 2px rgba(0,0,0,.25),inset 0 2px 4px rgba(0,0,0,.3);"
"position:relative}"
".slider:before{content:'';position:absolute;width:26px;height:26px;"
"top:3px;left:3px;background:#fff;border-radius:50%;"
"box-shadow:0 2px 5px rgba(0,0,0,.45);"
"transition:left .25s ease}"
"input:checked+.slider{background:#e94560}"
"input:checked+.slider:before{left:calc(100% - 29px)}"
".btn{padding:10px 28px;background:#e94560;color:#fff;border:none;border-radius:6px;"
"cursor:pointer;font-size:.95em;font-weight:bold;transition:.2s}"
".btn:hover{background:#c62828}"
".btn:active{transform:scale(.97)}"
".pm{width:40px;height:40px;border:1px solid #0f3460;background:#16213e;color:#4fc3f7;"
"font-size:1.4em;border-radius:8px;cursor:pointer;flex-shrink:0;line-height:1}"
".pm:active{background:#0f3460}"
".info-row{display:flex;justify-content:space-between;align-items:center;"
"padding:5px 0;border-bottom:1px solid #0f3460;font-size:.85em}"
".info-row:last-child{border-bottom:none}"
".info-label{color:#aaa}"
".info-val{color:#eee;font-weight:bold}"
".sh{text-align:center;padding:6px 2px;border-radius:4px;cursor:pointer;"
"font-size:.7em;line-height:1.3;user-select:none;border:2px solid #0f3460;background:#1a1a2e}"
".sh .ht{color:#aaa;font-size:.85em}"
".sh .tt{font-weight:bold;color:#4fc3f7}"
".sh.sel{border-color:#e94560}"
".sh.now{background:#0f3460}"
".pipe{stroke:#37474f;stroke-width:4;fill:none;stroke-linecap:round;stroke-linejoin:round}"
".pipe.hot{stroke:#e53935}"
".pipe.cold{stroke:#42a5f5}"
".pipe.flow{stroke-dasharray:8 6;animation:pflow .5s linear infinite}"
".pipe.idle{stroke-dasharray:12 4;animation:pidle 2s ease-in-out infinite}"
"@keyframes pflow{to{stroke-dashoffset:-14}}"
"@keyframes pidle{0%,100%{stroke-opacity:.3}50%{stroke-opacity:1}}"
".boxa{fill:#1a1a2e;stroke:#37474f;stroke-width:2}"
".boxa.on{stroke:#4fc3f7}"
".boxa.fl{stroke:#ff9800;fill:#1a1a2e;animation:flglow 1s ease-in-out infinite alternate}"
".boxa.go{stroke:#4caf50}"
".boxa.stop{stroke:#f44336}"
".mode-radio{display:flex;gap:4px;margin:4px 0}"
".mode-radio input{display:none}"
".mode-radio label{padding:7px 14px;background:#16213e;color:#aaa;"
"border:1px solid #0f3460;border-radius:6px;cursor:pointer;"
"font-size:.82em;text-align:center;flex:1;white-space:nowrap}"
".mode-radio input:checked+label{background:#0f3460;color:#4fc3f7;"
"border-color:#4fc3f7;font-weight:bold}"
"@keyframes flglow{from{stroke:#ff9800}to{stroke:#e65100}}"
".flame-icon{transform-box:fill-box;transform-origin:center bottom}"
".flame-icon.on{animation:flwave .4s ease-in-out infinite alternate}"
"@keyframes flwave{from{transform:scaleY(1) scaleX(1)}to{transform:scaleY(1.2) scaleX(.85)}}"
".pump-txt.on{fill:#4fc3f7;animation:pspin 1s linear infinite;transform-box:fill-box;transform-origin:center}"
"@keyframes pspin{to{transform:rotate(360deg)}}"
".tab-bar{display:flex;gap:2px;margin-bottom:10px;overflow-x:auto}"
".tab-bar button{padding:8px 18px;background:#16213e;color:#aaa;border:1px solid #0f3460;"
"border-bottom:none;border-radius:6px 6px 0 0;cursor:pointer;font-size:.85em;white-space:nowrap}"
".tab-bar button:hover{color:#4fc3f7;border-color:#4fc3f7}"
".tab-bar button.active{background:#0f3460;color:#4fc3f7;border-color:#4fc3f7;font-weight:bold}"
".tab-content{display:block}"
".log-entry{display:flex;gap:8px;padding:5px 0;border-bottom:1px solid rgba(15,52,96,.5);font-size:.8em}"
".log-entry .lt{flex:0 0 60px;color:#7986cb}"
".log-entry .lm{flex:1}"
".log-cat0 .lm{color:#90a4ae}"
".log-cat1 .lm{color:#a5d6a7}"
".log-cat2 .lm{color:#ffcc80}"
".log-cat3 .lm{color:#4fc3f7}"
".log-cat4 .lm{color:#e57373}"
".log-filter{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}"
".log-filter button{padding:3px 10px;border:1px solid #0f3460;border-radius:12px;background:#1a1a2e;color:#aaa;"
"cursor:pointer;font-size:.75em}"
".log-filter button.on0{background:#546e7a;color:#fff}"
".log-filter button.on1{background:#2e7d32;color:#fff}"
".log-filter button.on2{background:#e65100;color:#fff}"
".log-filter button.on3{background:#0d47a1;color:#fff}"
".log-filter button.on4{background:#b71c1c;color:#fff}"
"#log_list{max-height:60vh;overflow-y:auto;padding-right:4px}"
".corr-table{width:100%;border-collapse:collapse;font-size:.8em;margin-top:6px}"
".corr-table th{padding:4px 6px;text-align:left;color:#aaa;border-bottom:1px solid #0f3460;font-weight:normal}"
".corr-table td{padding:4px 6px;border-bottom:1px solid rgba(15,52,96,.3)}"
".corr-table tr:hover{background:rgba(79,195,247,.08)}"
".corr-val{color:#4fc3f7;font-weight:bold}"
".corr-diff-pos{color:#a5d6a7}"
".corr-diff-neg{color:#ef5350}"
"</style>"
"</head>"
"<body>"
"<div class='header'>"
"<h1>Baxi duo-tec compact &mdash; Управление</h1>"
"<div class='sub'>OpenTherm Gateway | ESP32 | WiFi</div>"
"</div>"
"<div class='container'>"
"<div class='tab-bar'>"
"<button data-tab='status'  onclick='switchTab(this)'>Статус</button>"
"<button data-tab='log'     onclick='switchTab(this)'>Журнал</button>"
"<button data-tab='stats'   onclick='switchTab(this)'>Статистика</button>"
"<button data-tab='control' onclick='switchTab(this)'>Управление</button>"
"<button data-tab='info'    onclick='switchTab(this)'>Инфо</button>"
"</div>"
"<div id='tab-status' class='tab-content'>"
"<div class='section' style='margin-top:0'>"
"<div style='display:flex;justify-content:space-between;align-items:center'>"
"<h2 style='margin:0;border:none;padding:0'>Статус котла</h2>"
"<span id='conn_badge' class='badge off'>Нет связи</span>"
"</div>"
"<div class='status-row' style='margin-top:12px'>"
"<span id='b_flame' class='badge off'>Горелка</span>"
"<span id='b_ch'    class='badge off'>Отопление</span>"
"<span id='b_dhw'   class='badge off'>Бойлер КН</span>"
"<span id='b_fault' class='badge off'>Авария</span>"
"<button id='btn_reset' class='btn' style='background:#c62828;font-size:.75em;padding:4px 10px;display:none;margin-left:8px' onclick='resetFault()'>Сброс</button>"
"</div>"
"</div>"
"<div class='section'>"
"<h2>Схема котла</h2>"
"<div style='overflow-x:auto'>"
"<svg viewBox='0 0 650 240' xmlns='http://www.w3.org/2000/svg' style='width:100%;min-width:500px;display:block;margin:0 auto'>"
"<path id='pfl' class='pipe' d='M95,85 H125'/>"
"<path id='ps1' class='pipe' d='M225,85 H296'/>"
"<path id='pcf' class='pipe' d='M310,71 V37 H430'/>"
"<path id='pdf' class='pipe' d='M310,99 V170 H430'/>"
"<path id='pcm' class='pipe' d='M530,37 H600 V208'/>"
"<path id='pdm' class='pipe' d='M530,170 H600 V208'/>"
"<path id='prt' class='pipe' d='M600,208 H272'/>"
"<path id='prp' class='pipe' d='M228,208 H175 V125'/>"
"<rect id='box_brn' class='boxa' x='10' y='55' width='85' height='60' rx='6'/>"
"<text x='52' y='72' text-anchor='middle' font-size='12' fill='#aaa'>\u0413\u043e\u0440\u0435\u043b\u043a\u0430</text>"
"<text x='52' y='90' text-anchor='middle' font-size='18' id='t_fire' class='flame-icon'>\U0001F525</text>"
"<text x='52' y='108' text-anchor='middle' font-size='13' font-weight='bold' fill='#4fc3f7' id='t_mod'>--%</text>"
"<rect id='box_hx' class='boxa' x='125' y='45' width='100' height='80' rx='6'/>"
"<text x='175' y='66' text-anchor='middle' font-size='10' fill='#888'>\u0422\u0435\u043f\u043b\u043e-</text>"
"<text x='175' y='78' text-anchor='middle' font-size='10' fill='#888'>\u043e\u0431\u043c\u0435\u043d\u043d\u0438\u043a</text>"
"<text x='175' y='96' text-anchor='middle' font-size='13' fill='#ef6c00' id='t_ft'>\u25b2 --\u00b0C</text>"
"<text x='175' y='114' text-anchor='middle' font-size='13' fill='#42a5f5' id='t_rt'>\u25bc --\u00b0C</text>"
/* 3-ходовой клапан: круглый корпус + порты + поворотная ручка */
"<circle id='box_vlv' cx='310' cy='85' r='14' class='boxa'/>"
"<rect id='vlv_port_in' x='288' y='80' width='8' height='10' class='boxa'/>"
"<rect id='vlv_port_ch' x='305' y='64' width='10' height='8' class='boxa'/>"
"<rect id='vlv_port_dhw' x='305' y='98' width='10' height='8' class='boxa'/>"
"<g id='vlv_handle'>"
"<line x1='310' y1='85' x2='310' y2='73' stroke='#aaa' stroke-width='3' stroke-linecap='round'/>"
"<circle cx='310' cy='73' r='3' fill='#aaa'/>"
"</g>"
"<text x='310' y='92' text-anchor='middle' font-size='9' fill='#aaa' id='t_vlv'></text>"
"<rect id='box_ch' class='boxa' x='430' y='10' width='100' height='55' rx='6'/>"
"<text x='480' y='30' text-anchor='middle' font-size='13' fill='#aaa'>\u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u0435</text>"
"<text x='480' y='52' text-anchor='middle' font-size='12' fill='#ef6c00' id='t_chsp'>\u0443\u0441\u0442. --\u00b0C</text>"
"<rect id='box_dhw' class='boxa' x='430' y='142' width='100' height='55' rx='6'/>"
"<text x='480' y='158' text-anchor='middle' font-size='13' fill='#aaa'>\u0411\u043e\u0439\u043b\u0435\u0440 \u041a\u041d</text>"
"<text x='480' y='177' text-anchor='middle' font-size='14' fill='#4fc3f7' id='t_dht'>--\u00b0C</text>"
"<text x='480' y='193' text-anchor='middle' font-size='11' fill='#ff7043' id='t_dhwsp'>\u0443\u0441\u0442. --\u00b0C</text>"
"<circle id='box_pump' class='boxa' cx='250' cy='208' r='22'/>"
"<text x='250' y='204' text-anchor='middle' font-size='20' fill='#aaa' id='t_pump' class='pump-txt'>\u21bb</text>"
"<text x='250' y='218' text-anchor='middle' font-size='9' fill='#aaa'>\u041d\u0430\u0441\u043e\u0441</text>"
"<text x='430' y='225' text-anchor='middle' font-size='11' fill='#555'>\u043e\u0431\u0440\u0430\u0442\u043a\u0430</text>"
"</svg>"
"</div>"
"</div>"
"<div class='grid'>"
"<div class='card'><h3>Подача CH</h3>"
"<span class='value' id='ch_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"<div class='card'><h3>Обратка CH</h3>"
"<span class='value' id='ret_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"<div class='card'><h3>Бойлер КН</h3>"
"<span class='value' id='dhw_temp'>--.-</span><span class='unit'>&deg;C</span>"
"<div id='dhw_session' style='font-size:.7em;color:#4fc3f7;margin-top:2px;display:none'></div></div>"
"<div class='card'><h3>Модуляция</h3>"
"<span class='value' id='modulation'>--</span><span class='unit'>%</span></div>"
"<div class='card'><h3>3-ход. клапан</h3>"
"<span class='value' style='font-size:1.1em' id='valve_state'>--</span></div>"
"<div class='card'><h3>T1</h3>"
"<span class='value' id='t1_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"<div class='card'><h3>T2</h3>"
"<span class='value' id='t2_temp'>--.-</span><span class='unit'>&deg;C</span></div>"
"</div>"
"</div>"  /* close tab-status */
"<div id='tab-log' class='tab-content' style='display:none'>"
"<div class='section'>"
"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;flex-wrap:wrap;gap:4px'>"
"<h2 style='margin:0;border:none;padding:0'>Журнал событий</h2>"
"<span id='log_time' style='font-size:.85em;color:#7986cb'>--:--:--</span>"
"<div class='log-filter' id='log_filter'>"
"<button class='on0' onclick='logFilter(0,this)'>Система</button>"
"<button class='on1' onclick='logFilter(1,this)'>Польз.</button>"
"<button class='on2' onclick='logFilter(2,this)'>Оборуд.</button>"
"<button class='on3' onclick='logFilter(3,this)'>Режимы</button>"
"<button class='on4' onclick='logFilter(4,this)'>Запуск</button>"
"<button class='on' onclick='logFilter(-1,this)'>ВСЕ</button>"
"</div>"
"</div>"
"<div id='log_list'></div>"
"</div>"
"</div>"
"<div id='tab-stats' class='tab-content' style='display:none'>"
"<div class='section'>"
"<h2>Модуляция</h2>"
"<div id='stats_mod' class='info-row' style='display:grid;grid-template-columns:repeat(4,1fr);gap:4px;font-size:.8em'></div>"
"<button class='btn' style='margin-top:6px;padding:2px 10px;font-size:.7em' onclick='resetModStats()'>Сбросить статистику модуляции</button>"
"</div>"
"<div class='section'>"
"<h2>Циклы горения</h2>"
"<div id='stats_cyc'></div>"
"<button class='btn' style='margin-top:6px;padding:2px 10px;font-size:.7em' onclick='resetCycleStats()'>Сбросить статистику циклов</button>"
"</div>"
"<div class='section'>"
"<h2>Расход газа</h2>"
"<button class='btn' style='margin-top:6px;padding:2px 10px;font-size:.7em' onclick='resetGasStats()'>Сбросить статистику газа</button>"
"<div id='stats_gas'></div>"
"</div>"
"<div class='section'>"
"<h2>Сверка счётчика</h2>"
"<div class='ctrl-row'>"
"<label>Нач. показание</label>"
"<input type='number' id='meter_base' value='0' step='0.001' min='0' "
"onfocus='setDirtyField(\"mb\",true)' onblur='setDirtyField(\"mb\",false)' "
"style='width:110px;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;border-radius:4px;padding:4px;font-size:.9em;text-align:center'>"
"<button class='btn' style='padding:4px 12px;font-size:.75em' onclick='setMeterBase()'>Установить</button>"
"<span id='mb_msg' style='font-size:.8em;color:#4caf50'></span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Текущее расчётное</label>"
"<span class='info-val' id='meter_total' style='font-size:1.1em'>--.--</span><span style='color:#aaa;font-size:.85em'> м&#179;</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Показание счётчика</label>"
"<input type='number' id='meter_reading' step='0.001' min='0' "
"style='width:110px;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;border-radius:4px;padding:4px;font-size:.9em;text-align:center'>"
"<button class='btn' style='padding:4px 12px;font-size:.75em' onclick='recordCorrection()'>Записать</button>"
"<span id='mc_msg' style='font-size:.8em;color:#4caf50'></span>"
"</div>"
"<div style='margin-top:8px'>"
"<div style='font-size:.8em;color:#aaa;margin-bottom:4px'>Журнал сверки</div>"
"<div id='corr_log' style='max-height:240px;overflow-y:auto'><div style='color:#555;font-style:italic;padding:8px'>нет коррекций</div></div>"
"</div>"
"</div>"
"</div>"
"<div id='tab-control' class='tab-content' style='display:none'>"
/* ======== Отопление ======== */
"<div class='section'>"
"<h2>Отопление</h2>"
"<div class='ctrl-row'>"
"<label>Разрешение</label>"
"<label class='toggle'><input type='checkbox' id='ch_en' onchange='setDirty()'>"
"<span class='slider'></span></label>"
"<span id='ch_en_lbl' style='font-size:.85em;color:#aaa'>Выкл</span>"
"</div>"
"<div class='ctrl-row' style='margin-top:8px'>"
"<label>Режим</label>"
"<div class='mode-radio'>"
"<input type='radio' name='ch_mode' id='ch_mode_0' value='0' onchange='switchMode()'>"
"<label for='ch_mode_0'>Ручной</label>"
"<input type='radio' name='ch_mode' id='ch_mode_1' value='1' onchange='switchMode()'>"
"<label for='ch_mode_1'>ПИД</label>"
"<input type='radio' name='ch_mode' id='ch_mode_2' value='2' onchange='switchMode()'>"
"<label for='ch_mode_2'>Расписание</label>"
"</div>"
"</div>"
/* панель Ручной */
"<div id='pnl_manual' style='display:none'>"
"<div class='ctrl-row'>"
"<label>Уставка CH</label>"
"<button class='pm' onclick='adj(\"ch_sp\",-1)'>−</button>"
"<input type='range' id='ch_sp' min='20' max='80' step='1' value='60' "
"oninput='updateLabel(\"ch_sp_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"ch_sp\",1)'>+</button>"
"<span class='temp-display'><span id='ch_sp_v'>60</span>&deg;C</span>"
"</div>"
"</div>"
/* панель ПИД */
"<div id='pnl_pid' style='display:none'>"
"<div class='ctrl-row'>"
"<label>Цель комнаты</label>"
"<input type='range' id='pid_target' min='16' max='28' step='0.5' value='22' "
"oninput='updateLabel(\"pid_target_v\",this.value)' onchange='setDirty()'>"
"<span class='temp-display'><span id='pid_target_v'>22.0</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Датчик</label>"
"<div style='display:flex;gap:8px;align-items:center'>"
"<label style='font-size:.85em;color:#aaa'>T1</label>"
"<label class='toggle'><input type='checkbox' id='pid_sensor' onchange='setDirty()'><span class='slider'></span></label>"
"<label style='font-size:.85em;color:#aaa'>T2</label>"
"</div>"
"</div>"
"<div class='ctrl-row'>"
"<label>Kp</label>"
"<button class='pm' onclick='adj(\"pid_kp\",-0.1)'>−</button>"
"<input type='range' id='pid_kp' min='0' max='20' step='0.1' value='2' "
"oninput='updateLabel(\"pid_kp_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"pid_kp\",0.1)'>+</button>"
"<span class='temp-display'><span id='pid_kp_v'>2.0</span></span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Ki (&times;0.001)</label>"
"<button class='pm' onclick='adj(\"pid_ki\",-1)'>−</button>"
"<input type='range' id='pid_ki' min='0' max='200' step='1' value='10' "
"oninput='updateLabel(\"pid_ki_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"pid_ki\",1)'>+</button>"
"<span class='temp-display'><span id='pid_ki_v'>10</span></span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Kd</label>"
"<button class='pm' onclick='adj(\"pid_kd\",-0.1)'>−</button>"
"<input type='range' id='pid_kd' min='0' max='20' step='0.1' value='0' "
"oninput='updateLabel(\"pid_kd_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"pid_kd\",0.1)'>+</button>"
"<span class='temp-display'><span id='pid_kd_v'>0.0</span></span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Интервал (с)</label>"
"<select id='pid_dt' onchange='setDirty()' style='font-size:.9em;padding:2px 6px;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;border-radius:4px'>"
"<option value='30'>30</option><option value='60' selected>60</option>"
"<option value='90'>90</option><option value='120'>120</option>"
"</select>"
"</div>"
"<div class='ctrl-row'>"
"<label>Защита цикла (с)</label>"
"<select id='pid_lockout' onchange='setDirty()' style='font-size:.9em;padding:2px 6px;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;border-radius:4px'>"
"<option value='120'>120</option><option value='300' selected>300</option>"
"<option value='600'>600</option><option value='900'>900</option>"
"</select>"
"</div>"
"<div class='ctrl-row'>"
"<label>Гистерезис CH</label>"
"<button class='pm' onclick='adj(\"pid_hyst\",-0.1)'>−</button>"
"<input type='range' id='pid_hyst' min='0.1' max='3.0' step='0.1' value='0.5' "
"oninput='updateLabel(\"pid_hyst_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"pid_hyst\",0.1)'>+</button>"
"<span class='temp-display'><span id='pid_hyst_v'>0.5</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<span id='pid_status' style='font-size:.85em;color:#aaa'></span>"
"</div>"
"</div>"
/* панель Расписание */
"<div id='pnl_sched' style='display:none'>"
"<div id='sched_grid' style='display:grid;grid-template-columns:repeat(12,1fr);gap:3px;margin:4px 0'></div>"
"<div class='ctrl-row' style='margin-top:6px'>"
"<label>Температура</label>"
"<button class='pm' onclick='adj(\"sched_t\",-1)'>−</button>"
"<input type='range' id='sched_t' min='20' max='80' step='1' value='30' "
"oninput='updateLabel(\"sched_t_v\",this.value)'>"
"<button class='pm' onclick='adj(\"sched_t\",1)'>+</button>"
"<span class='temp-display'><span id='sched_t_v'>30</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<button class='btn' style='font-size:.85em;padding:8px 16px' onclick='schedSet()'>Установить</button>"
"<button class='btn' style='font-size:.85em;padding:8px 16px' onclick='schedSelectAll()'>Выбрать все</button>"
"<button class='btn' style='font-size:.85em;padding:8px 16px;background:#546e7a' onclick='schedClear()'>Снять</button>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<button class='btn' onclick='schedSave()'>Сохранить</button>"
"<span id='sched_msg' style='font-size:.85em;color:#4caf50;margin-left:8px'></span>"
"</div>"
"<div class='ctrl-row' style='margin-top:4px'>"
"<span id='sched_status' style='font-size:.75em;color:#aaa'></span>"
"</div>"
"</div>"
"<div class='ctrl-row' style='margin-top:10px'>"
"<label></label>"
"<button class='btn' onclick='applyControl()'>Применить</button>"
"<span id='apply_msg' style='font-size:.85em;color:#4caf50;margin-left:8px'></span>"
"</div>"
"</div>"
/* ======== Бойлер БКН ======== */
"<div class='section'>"
"<h2>Бойлер БКН</h2>"
"<div class='ctrl-row'>"
"<label>Разрешение</label>"
"<label class='toggle'><input type='checkbox' id='dhw_en' onchange='setDirty()'>"
"<span class='slider'></span></label>"
"<span id='dhw_en_lbl' style='font-size:.85em;color:#aaa'>Выкл</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Уставка БКН</label>"
"<button class='pm' onclick='adj(\"dhw_sp\",-1)'>−</button>"
"<input type='range' id='dhw_sp' min='40' max='80' step='1' value='60' "
"oninput='updateLabel(\"dhw_sp_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"dhw_sp\",1)'>+</button>"
"<span class='temp-display'><span id='dhw_sp_v'>60</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label>Гистерезис БКН</label>"
"<button class='pm' onclick='adj(\"dhw_hyst\",-0.5)'>−</button>"
"<input type='range' id='dhw_hyst' min='0.5' max='10' step='0.5' value='2' "
"oninput='updateLabel(\"dhw_hyst_v\",this.value)' onchange='setDirty()'>"
"<button class='pm' onclick='adj(\"dhw_hyst\",0.5)'>+</button>"
"<span class='temp-display'><span id='dhw_hyst_v'>2.0</span>&deg;C</span>"
"</div>"
"<div class='ctrl-row'>"
"<label></label>"
"<button class='btn' onclick='applyDHW()'>Применить</button>"
"<span id='dhw_apply_msg' style='font-size:.85em;color:#4caf50;margin-left:8px'></span>"
"</div>"
"</div>"
"<div style='text-align:center;margin:20px 0 8px'>"
"<button class='btn' style='background:#c62828' onclick='shutdownBoiler()'>Выключить котёл</button>"
"<span id='shutdown_msg' style='font-size:.85em;margin-left:8px'></span>"
"</div>"
"</div>"
"<div id='tab-info' class='tab-content' style='display:none'>"
"<div class='section'>"
"<h2>Диагностика</h2>"
"<div class='info-row'><span class='info-label'>Код ошибки (OEM)</span>"
"<span class='info-val' id='oem_fault'>--</span></div>"
"<div class='info-row'><span class='info-label'>Флаги ошибок (ASF)</span>"
"<span class='info-val' id='asf_flags'>--</span></div>"
"<div class='info-row'><span class='info-label'>OEM диагностика</span>"
"<span class='info-val' id='oem_diag'>--</span></div>"
"<div class='info-row'><span class='info-label'>Уставка CH (границы)</span>"
"<span class='info-val' id='ch_bounds'>--</span></div>"
"<div class='info-row'><span class='info-label'>Уставка DHW (границы)</span>"
"<span class='info-val' id='dhw_bounds'>--</span></div>"
"</div>"
"<div class='section'>"
"<h2>Информация об устройстве</h2>"
"<div class='info-row'><span class='info-label'>IP адрес</span>"
"<span class='info-val' id='device_ip'>...</span></div>"
"<div class='info-row'><span class='info-label'>Версия ПО котла</span>"
"<span class='info-val' id='slave_ver'>--</span></div>"
"<div class='info-row'><span class='info-label'>Версия OT</span>"
"<span class='info-val' id='ot_ver'>--</span></div>"
"<div class='info-row'><span class='info-label'>Платформа</span>"
"<span class='info-val'>ESP32 + WiFi</span></div>"
"<div class='info-row'><span class='info-label'>Часовой пояс</span>"
"<span class='info-val' style='display:flex;align-items:center;gap:6px'>"
"UTC+<input type='number' id='tz_val' value='3' min='-12' max='14' "
"onfocus='setDirtyField(\"tz\",true)' onblur='setDirtyField(\"tz\",false)' "
"style='width:50px;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;"
"border-radius:4px;padding:4px;font-size:.9em;text-align:center'>"
"<button class='btn' style='padding:4px 12px;font-size:.75em' onclick='setTz()'>OK</button>"
"<span id='tz_msg' style='font-size:.8em;color:#4caf50'></span>"
"</span></div>"
"<div class='info-row'><span class='info-label'>NTP сервер 1</span>"
"<span class='info-val' style='display:flex;align-items:center;gap:6px;flex:1;max-width:400px'>"
"<input type='text' id='sntp_srv0' value='pool.ntp.org' "
"onfocus='setDirtyField(\"sntp0\",true)' onblur='setDirtyField(\"sntp0\",false)' "
"style='flex:1;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;"
"border-radius:4px;padding:4px;font-size:.85em'>"
"<input type='text' id='sntp_srv1' value='time.google.com' "
"onfocus='setDirtyField(\"sntp1\",true)' onblur='setDirtyField(\"sntp1\",false)' "
"style='flex:1;background:#1a1a2e;color:#4fc3f7;border:1px solid #0f3460;"
"border-radius:4px;padding:4px;font-size:.85em'>"
"<button class='btn' style='padding:4px 12px;font-size:.75em' onclick='setSntp()'>OK</button>"
"<span id='sntp_msg' style='font-size:.8em;color:#4caf50'></span>"
"</span></div>"
"<div class='info-row'><span class='info-label'>Время ESP32</span>"
"<span class='info-val' id='esp_time'>--:--:--</span></div>"
"<div class='info-row'><span class='info-label'>Обновление данных</span>"
"<span class='info-val'>каждые 2 сек</span></div>"
"</div>"
"</div>"  /* close tab-info */
"</div>"
"<script>"
"var dirty=false;var dirtyFields={tz:false,mb:false,sntp0:false,sntp1:false};"
"document.getElementById('device_ip').textContent=window.location.hostname;"
"function fmt1(v){return isNaN(v)?'--.-':parseFloat(v).toFixed(1);}"
"function fmt0(v){return isNaN(v)?'--':Math.round(v);}"
"function badge(id,on,onTxt,offTxt,warn){"
"var el=document.getElementById(id);"
"el.className='badge '+(warn?'warn':(on?'on':'off'));"
"el.textContent=on?onTxt:offTxt;}"
"function updateLabel(id,v){document.getElementById(id).textContent=v;}"
"function adj(id,d){var s=document.getElementById(id);"
"var min=parseFloat(s.min),max=parseFloat(s.max),step=parseFloat(s.step)||1;"
"var v=(parseFloat(s.value)||min)+d;"
"v=Math.round(v/step)*step;"
"v=Math.max(min,Math.min(max,v));"
"s.value=v;updateLabel(id+'_v',v.toFixed(step>=1?0:1));setDirty();}"
"function setTz(){"
"var v=parseInt(document.getElementById('tz_val').value);"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({tz_offset:v})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('tz_msg');"
"m.textContent=d.ok?'OK':'Err';"
"setTimeout(function(){m.textContent='';},2000);"
"if(d.ok){dirtyFields.tz=false;document.getElementById('tz_val').style.background='#1a1a2e';}"
"})['catch'](function(){});}"

"function setSntp(){"
"var s0=document.getElementById('sntp_srv0').value.trim();"
"var s1=document.getElementById('sntp_srv1').value.trim();"
"if(!s0)s0='pool.ntp.org';"
"if(!s1)s1='time.google.com';"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({sntp_server0:s0,sntp_server1:s1})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('sntp_msg');"
"m.textContent=d.ok?'OK':'Err';"
"setTimeout(function(){m.textContent='';},2000);"
"if(d.ok){dirtyFields.sntp0=false;dirtyFields.sntp1=false;"
"document.getElementById('sntp_srv0').style.background='#1a1a2e';"
"document.getElementById('sntp_srv1').style.background='#1a1a2e';}"
"})['catch'](function(){});}"

"function setMeterBase(){"
"var v=parseFloat(document.getElementById('meter_base').value);"
"if(isNaN(v)||v<0)v=0;"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({gas_meter_base:v})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('mb_msg');"
"m.textContent=d.ok?'OK':'Err';"
"setTimeout(function(){m.textContent='';},2000);"
"if(d.ok){dirtyFields.mb=false;document.getElementById('meter_base').style.background='#1a1a2e';}"
"})['catch'](function(){});}"
"function recordCorrection(){"
"var v=parseFloat(document.getElementById('meter_reading').value);"
"if(isNaN(v)||v<0){alert('Введите корректное показание');return;}"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({gas_meter_correct:v})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('mc_msg');"
"m.textContent=d.ok?'OK':'Err';"
"setTimeout(function(){m.textContent='';},2000);"
"if(d.ok)document.getElementById('meter_reading').value='';"
"})['catch'](function(){});}"
"function resetModStats(){"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({reset_mod_stats:1})})"
"['catch'](function(){});}"
"function resetCycleStats(){"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({reset_cycle_stats:1})})"
"['catch'](function(){});}"
"function resetGasStats(){"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({reset_gas_stats:1})})"
"['catch'](function(){});}"
"function setDirty(){"
"dirty=true;"
"document.getElementById('ch_en_lbl').textContent=document.getElementById('ch_en').checked?'Вкл':'Выкл';"
"document.getElementById('dhw_en_lbl').textContent=document.getElementById('dhw_en').checked?'Вкл':'Выкл';}"
"function setDirtyField(fieldId,on){"
"dirtyFields[fieldId]=on;"
"var el;"
"if(fieldId==='tz')el=document.getElementById('tz_val');"
"else if(fieldId==='mb')el=document.getElementById('meter_base');"
"else if(fieldId==='sntp0')el=document.getElementById('sntp_srv0');"
"else if(fieldId==='sntp1')el=document.getElementById('sntp_srv1');"
"if(el)el.style.background=on?'#2a1a2e':'#1a1a2e';}"
"function switchMode(){"
"var m=parseInt(document.querySelector('input[name=\"ch_mode\"]:checked').value);"
"document.getElementById('pnl_manual').style.display=m==0?'block':'none';"
"document.getElementById('pnl_pid').style.display=m==1?'block':'none';"
"document.getElementById('pnl_sched').style.display=m==2?'block':'none';"
"setDirty();}"
"function applyControl(){"
"var data={"
"ch_enable:document.getElementById('ch_en').checked?1:0,"
"ch_mode:parseInt(document.querySelector('input[name=\"ch_mode\"]:checked').value),"
"ch_setpoint:parseInt(document.getElementById('ch_sp').value),"
"pid_kp:parseFloat(document.getElementById('pid_kp').value),"
"pid_ki:parseFloat(document.getElementById('pid_ki').value)/1000,"
"pid_kd:parseFloat(document.getElementById('pid_kd').value),"
"pid_dt_sec:parseInt(document.getElementById('pid_dt').value),"
"pid_room_sensor:document.getElementById('pid_sensor').checked?1:0,"
"pid_target_room:parseFloat(document.getElementById('pid_target').value),"
"pid_cycle_lockout:parseInt(document.getElementById('pid_lockout').value),"
"pid_hysteresis:parseFloat(document.getElementById('pid_hyst').value)};"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(data)})"
".then(function(r){return r.json();})"
".then(function(d){"
"var msg=d.ok?'Применено':'Ошибка';"
"var clr=d.ok?'#4caf50':'#f44336';"
"var m1=document.getElementById('apply_msg');"
"if(m1){m1.textContent=msg;m1.style.color=clr;setTimeout(function(){m1.textContent='';},3000);}"
"dirty=false;"
"})['catch'](function(){"
"var m1=document.getElementById('apply_msg');"
"if(m1)m1.textContent='Ошибка связи';});}"
"function applyDHW(){"
"var data={"
"dhw_enable:document.getElementById('dhw_en').checked?1:0,"
"dhw_setpoint:parseInt(document.getElementById('dhw_sp').value),"
"dhw_hysteresis:parseFloat(document.getElementById('dhw_hyst').value)};"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(data)})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('dhw_apply_msg');"
"if(m){m.textContent=d.ok?'Применено':'Ошибка';"
"m.style.color=d.ok?'#4caf50':'#f44336';"
"setTimeout(function(){m.textContent='';},3000);}"
"})['catch'](function(){"
"var m=document.getElementById('dhw_apply_msg');"
"if(m)m.textContent='Ошибка связи';});}"
"function shutdownBoiler(){"
"if(!confirm('Выключить котёл? После этого можно отключать ESP32.'))return;"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ch_enable:0,dhw_enable:0})})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('shutdown_msg');"
"m.textContent=d.ok?'Котёл выключен':'Ошибка';"
"m.style.color=d.ok?'#4caf50':'#f44336';"
"dirty=false;"
"})['catch'](function(){"
"document.getElementById('shutdown_msg').textContent='Ошибка связи';});}"
"function resetFault(){"
"fetch('/api/control',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({fault_reset:1})})"
".then(function(r){return r.json();})"
".then(function(){})['catch'](function(){});}"
"function setP(id,on,a){var e=document.getElementById(id);if(e)e.setAttribute('class','pipe'+(on?(a||''):''));}"
"function poll(){"
"fetch('/api/status')"
".then(function(r){return r.json();})"
".then(function(d){"
"badge('conn_badge',d.connected,'Подключено','Нет связи',false);"
"badge('b_flame',d.flame,'Горелка ON','Горелка OFF',false);"
"var chEff=d.ch_enable&&(d.ch_mode==1?d.pid_ch_enabled:true);"
"badge('b_ch',d.ch_active,'CH работает',chEff?'CH разрешён':'CH запрещён',!chEff);"
"badge('b_dhw',d.dhw_active,'Бойлер нагрев',d.dhw_enable?'БКН разрешён':'БКН запрещён',!d.dhw_enable);"
"badge('b_fault',d.fault,'АВАРИЯ','Авария нет',d.fault);"
"document.getElementById('btn_reset').style.display=d.fault?'inline-block':'none';"
"document.getElementById('ch_temp').textContent=fmt1(d.ch_temp);"
"document.getElementById('ret_temp').textContent=fmt1(d.return_temp);"
"document.getElementById('dhw_temp').textContent=fmt1(d.dhw_temp);"
"document.getElementById('t1_temp').textContent=fmt1(d.t1_temp);"
"document.getElementById('t2_temp').textContent=fmt1(d.t2_temp);"
"var ds=document.getElementById('dhw_session');"
"if(d.dhw_pred_active){"
"var el=d.dhw_pred_elapsed;"
"var em=Math.floor(el/60),es=el%60;"
"var elapsed_str=em+':'+(es<10?'0':'')+es;"
"if(el<30){"
"ds.textContent='прошло '+elapsed_str+', прогноз появится через 30 сек';"
"ds.style.display='block';}else{"
"var lo=Math.max(0,Math.round((d.dhw_pred_remaining-d.dhw_pred_uncertainty)/60));"
"var hi=Math.round((d.dhw_pred_remaining+d.dhw_pred_uncertainty)/60);"
"if(hi==0){"
"ds.textContent='прошло '+elapsed_str+', осталось ~'+d.dhw_pred_remaining+' сек';"
"}else if(lo==hi){"
"ds.textContent='прошло '+elapsed_str+', осталось ~'+lo+' мин';"
"}else{"
"ds.textContent='прошло '+elapsed_str+', осталось '+lo+'–'+hi+' мин';"
"}"
"ds.style.display='block';}}"
"else if(d.dhw_last_session_sec>0){"
"var m=Math.floor(d.dhw_last_session_sec/60),s=d.dhw_last_session_sec%60;"
"ds.textContent='последний нагрев '+m+':'+(s<10?'0':'')+s;"
"ds.style.display='block';}"
"else{ds.style.display='none';}"
"/* PID status */"
"var pid_status=document.getElementById('pid_status');"
"if(d.ch_mode==1){"
"var sensor_name='T'+(d.pid_room_sensor?2:1);"
"if(d.pid_active){"
"var st=sensor_name+' \u043a\u043e\u043c\u043d. '+fmt1(d.pid_room_temp)+'\u00b0C, \u0446\u0435\u043b\u044c '+fmt1(d.pid_target_room)+'\u00b0C, \u0432\u044b\u0445\u043e\u0434 '+Math.round(d.pid_output)+'\u00b0C';"
"if(d.pid_cycle_locked){st+=', \u0411\u041b\u041e\u041a '+d.pid_remaining_lockout+'\u0441';}"
"else if(!d.pid_ch_enabled){st+=', CH \u043e\u0442\u043a\u043b (\u0433\u0438\u0441\u0442\u0435\u0440\u0435\u0437\u0438\u0441)';}"
"else{st+=', CH \u0440\u0430\u0437\u0440\u0435\u0448\u0451\u043d';}"
"pid_status.textContent=st;"
"}else{"
"pid_status.textContent='\u043d\u0435\u0442 \u0434\u0430\u043d\u043d\u044b\u0445 '+sensor_name;}"
"}else{"
"pid_status.textContent='';}"
"document.getElementById('modulation').textContent=fmt0(d.modulation);"
/* 3-ход. клапан: определяем положение из флага dhw_active */
"var vs=document.getElementById('valve_state');"
"vs.textContent=d.dhw_active?'\u2192 Бойлер':'\u2192 Отопление';"
"vs.style.color=d.dhw_active?'#4fc3f7':'#a5d6a7';"
/* Обновить границы слайдера бойлера из ответа котла (ID=48) */
"if(d.dhw_sp_max>d.dhw_sp_min&&d.dhw_sp_max>0){"
"var sl=document.getElementById('dhw_sp');"
"sl.min=d.dhw_sp_min;sl.max=d.dhw_sp_max;}"
"if(d.ch_sp_max>d.ch_sp_min&&d.ch_sp_max>0){"
"var cs=document.getElementById('ch_sp');"
"cs.min=d.ch_sp_min;cs.max=d.ch_sp_max;}"
"if(!dirty){"
"document.getElementById('ch_en').checked=!!d.ch_enable;"
"document.getElementById('dhw_en').checked=!!d.dhw_enable;"
"document.getElementById('ch_sp').value=d.ch_setpoint;"
"document.getElementById('ch_sp_v').textContent=Math.round(d.ch_setpoint);"
"document.getElementById('dhw_sp').value=d.dhw_setpoint;"
"document.getElementById('dhw_sp_v').textContent=Math.round(d.dhw_setpoint);"
"document.getElementById('dhw_hyst').value=d.dhw_hyst_on;"
"document.getElementById('dhw_hyst_v').textContent=d.dhw_hyst_on.toFixed(1);"
"var modeRadio=document.getElementById('ch_mode_'+d.ch_mode);"
"if(modeRadio)modeRadio.checked=true;"
"document.getElementById('pnl_manual').style.display=d.ch_mode==0?'block':'none';"
"document.getElementById('pnl_pid').style.display=d.ch_mode==1?'block':'none';"
"document.getElementById('pnl_sched').style.display=d.ch_mode==2?'block':'none';"
"document.getElementById('pid_sensor').checked=!!d.pid_room_sensor;"
"document.getElementById('pid_target').value=d.pid_target_room;"
"document.getElementById('pid_target_v').textContent=d.pid_target_room.toFixed(1);"
"document.getElementById('pid_kp').value=d.pid_kp;"
"document.getElementById('pid_kp_v').textContent=d.pid_kp.toFixed(1);"
"document.getElementById('pid_ki').value=Math.round(d.pid_ki*1000);"
"document.getElementById('pid_ki_v').textContent=Math.round(d.pid_ki*1000);"
"document.getElementById('pid_kd').value=d.pid_kd;"
"document.getElementById('pid_kd_v').textContent=d.pid_kd.toFixed(1);"
"document.getElementById('pid_hyst').value=d.pid_hysteresis;"
"document.getElementById('pid_hyst_v').textContent=d.pid_hysteresis.toFixed(1);"
"document.getElementById('ch_en_lbl').textContent=d.ch_enable?'Вкл':'Выкл';"
"document.getElementById('dhw_en_lbl').textContent=d.dhw_enable?'Вкл':'Выкл';}"
"if(d.time)document.getElementById('esp_time').textContent=d.time;"
"if(d.time)document.getElementById('log_time').textContent=d.time;"
"document.getElementById('oem_fault').textContent=d.oem_fault||'0';"
"document.getElementById('asf_flags').textContent='0x'+('0'+d.asf_flags.toString(16)).slice(-2);"
"document.getElementById('oem_diag').textContent=d.oem_diag||'0';"
"document.getElementById('ch_bounds').textContent=d.ch_sp_min+' .. '+d.ch_sp_max+' \\u00b0C';"
"document.getElementById('dhw_bounds').textContent=d.dhw_sp_min+' .. '+d.dhw_sp_max+' \\u00b0C';"
"document.getElementById('slave_ver').textContent='Type '+d.slave_type+', v'+d.slave_ver;"
"document.getElementById('ot_ver').textContent=d.ot_ver>0?d.ot_ver.toFixed(1):'N/A';"
"if(d.tz_offset!=null&&!dirtyFields.tz)document.getElementById('tz_val').value=d.tz_offset;"
"if(d.sntp_server0&&!dirtyFields.sntp0)document.getElementById('sntp_srv0').value=d.sntp_server0;"
"if(d.sntp_server1&&!dirtyFields.sntp1)document.getElementById('sntp_srv1').value=d.sntp_server1;"
"var fl=d.flame,pw=d.ch_active||d.dhw_active,dh=d.dhw_active;"
"var chA=pw&&!dh,dhA=pw&&dh,af=pw?' flow':(fl?' idle':'');"
"setP('pfl',fl,fl?(pw?' flow':' idle'):'');"
"setP('ps1',pw||fl,' hot'+af);"
"setP('pcf',chA,' hot'+(chA?' flow':''));setP('pdf',dhA,' hot'+(dhA?' flow':''));"
"setP('pcm',chA,' cold'+(chA?' flow':''));setP('pdm',dhA,' cold'+(dhA?' flow':''));"
"var rt=chA||dhA;setP('prt',rt,' cold'+(rt?' flow':''));setP('prp',rt,' cold'+(rt?' flow':''));"
"document.getElementById('box_brn').setAttribute('class','boxa'+(fl?' fl':''));"
"document.getElementById('t_fire').setAttribute('class','flame-icon'+(fl?' on':''));"
"document.getElementById('box_hx').setAttribute('class','boxa'+(pw?' on':''));"
"document.getElementById('box_pump').setAttribute('class','boxa'+(pw?' on':''));"
"document.getElementById('t_pump').setAttribute('class','pump-txt'+(pw?' on':''));"
"var chEna=d.ch_enable&&(d.ch_mode==1?d.pid_ch_enabled:true);"
"var dhwEna=d.dhw_enable;"
"var chCls='boxa'+(chEna?' go':' stop');"
"var dhwCls='boxa'+(dhwEna?' go':' stop');"
"var vPortCh='boxa'+(chEna?' go':' stop');"
"var vPortDhw='boxa'+(dhwEna?' go':' stop');"
"var anyGo=chEna||dhwEna;"
"var vVa=90,vHc=anyGo?'#4caf50':'#f44336',vTxt='\u25cb';"
"if(dhA){vVa=180;vTxt='\u25bc';}"
"else if(chA){vVa=0;vTxt='\u25b2';}"
"else if(dhwEna){vVa=180;vTxt='\u25bd';}"
"else if(chEna){vVa=0;vTxt='\u25b3';}"
"document.getElementById('box_vlv').setAttribute('class','boxa'+(pw?' on':''));"
"document.getElementById('vlv_port_ch').setAttribute('class',vPortCh);"
"document.getElementById('vlv_port_dhw').setAttribute('class',vPortDhw);"
"document.getElementById('box_ch').setAttribute('class',chCls);"
"document.getElementById('box_dhw').setAttribute('class',dhwCls);"
"document.getElementById('t_mod').textContent=fl?fmt1(d.modulation)+'%':'--';"
"document.getElementById('t_ft').textContent='\\u25b2 '+fmt1(d.ch_temp)+'\\u00b0';"
"document.getElementById('t_rt').textContent='\\u25bc '+fmt1(d.return_temp)+'\\u00b0';"
"document.getElementById('t_dht').textContent=fmt1(d.dhw_temp)+'\\u00b0';"
"document.getElementById('t_chsp').textContent='\\u0443\\u0441\\u0442. '+Math.round(d.ch_setpoint)+'\\u00b0C';"
"document.getElementById('t_dhwsp').textContent='\\u0443\\u0441\\u0442. '+Math.round(d.dhw_setpoint)+'\\u00b0C';"
"document.getElementById('t_vlv').textContent=vTxt;"
"document.getElementById('vlv_handle').setAttribute('transform','rotate('+vVa+',310,85)');"
"document.getElementById('vlv_handle').querySelector('line').setAttribute('stroke',vHc);"
"document.getElementById('vlv_handle').querySelector('circle').setAttribute('fill',vHc);"
"})['catch'](function(){badge('conn_badge',false,'','Нет связи',false);});}"
/* Расписание */
"var sTemps=[];"
"var sSel=[];"
"var schedDirty=false;"
"var schedLoaded=false;"
"function schedInit(){"
"var g=document.getElementById('sched_grid');"
"g.innerHTML='';"
"for(var i=0;i<24;i++){"
"var d=document.createElement('div');"
"d.className='sh';d.id='sh'+i;"
"d.innerHTML='<div class=\"ht\">'+String(i).padStart(2,'0')+'</div><div class=\"tt\" id=\"st'+i+'\">--</div>';"
"d.onclick=(function(idx){return function(){sSel[idx]=!sSel[idx];schedRender();};})(i);"
"g.appendChild(d);}"
"}"
"function schedRender(){"
"for(var i=0;i<24;i++){"
"var el=document.getElementById('sh'+i);"
"var cls='sh';"
"if(sSel[i])cls+=' sel';"
"el.className=cls;"
"document.getElementById('st'+i).textContent=sTemps[i]!=null?Math.round(sTemps[i]):'--';}}"
"function schedSet(){"
"var t=parseInt(document.getElementById('sched_t').value);"
"for(var i=0;i<24;i++){if(sSel[i])sTemps[i]=t;}"
"schedDirty=true;schedRender();}"
"function schedSelectAll(){for(var i=0;i<24;i++)sSel[i]=true;schedRender();}"
"function schedClear(){for(var i=0;i<24;i++)sSel[i]=false;schedRender();}"
"function schedSave(){"
"var data={enabled:1,temps:sTemps};"
"fetch('/api/schedule',{method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify(data)})"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('sched_msg');"
"m.textContent=d.ok?'Сохранено':'Ошибка';"
"m.style.color=d.ok?'#4caf50':'#f44336';"
"schedDirty=false;"
"setTimeout(function(){m.textContent='';},3000);"
"})['catch'](function(){"
"document.getElementById('sched_msg').textContent='Ошибка связи';});}"
"function schedPoll(){"
"fetch('/api/schedule')"
".then(function(r){return r.json();})"
".then(function(d){"
"if(!schedDirty){"
"sTemps=d.temps.slice();"
"schedRender();}"
"var h=d.hour;"
"for(var i=0;i<24;i++){var el=document.getElementById('sh'+i);"
"if(h==i)el.classList.add('now');else el.classList.remove('now');}"
"var st=document.getElementById('sched_status');"
"st.textContent=d.enabled?(h>=0?'Час: '+h+':00, уставка: '+Math.round(d.temps[h])+'\\u00b0C':'NTP...'):'Выкл';"
"})['catch'](function(){});}"
"for(var i=0;i<24;i++){sTemps.push(30);sSel.push(false);}"
"schedInit();schedPoll();setInterval(schedPoll,5000);"
"poll();"
"setInterval(poll,2000);"
"var logCatMask=0x1F;"
"var logLastTs='';"
"function switchTab(arg){"
"var name=typeof arg=='string'?arg:arg.getAttribute('data-tab');"
"var tabs=document.querySelectorAll('.tab-content');"
"for(var i=0;i<tabs.length;i++)tabs[i].style.display='none';"
"var t=document.getElementById('tab-'+name);"
"if(t)t.style.display='block';"
"var btns=document.querySelectorAll('.tab-bar button');"
"for(var i=0;i<btns.length;i++){"
"btns[i].className=btns[i].getAttribute('data-tab')==name?'active':'';}"
"if(name=='log')pollLog();}"
"function logFilter(cat,btn){"
"if(cat<0){"
"logCatMask=0x1F;"
"var btns=document.querySelectorAll('#log_filter button');"
"for(var i=0;i<btns.length-1;i++)btns[i].className='on'+i;"
"btns[btns.length-1].className='on';}"
"else{"
"logCatMask^=(1<<cat);"
"btn.className=(logCatMask&(1<<cat))?'on'+cat:'';"
"var all=document.querySelector('#log_filter button:last-child');"
"if(logCatMask==0x1F)all.className='on';else all.className='';}"
"pollLog();}"
"function pollLog(){"
"fetch('/api/log')"
".then(function(r){return r.json();})"
".then(function(d){"
"var lst=document.getElementById('log_list');"
"var h='';"
"var showed=0;"
"for(var i=0;i<d.events.length;i++){"
"var e=d.events[i];"
"if(!(logCatMask&(1<<e.c)))continue;"
"showed++;"
"h+='<div class=\"log-entry log-cat'+e.c+'\">'"
"+'<span class=\"lt\">'+e.t+'</span>'"
"+'<span class=\"lm\">'+e.m+'</span>'"
"+'</div>';}"
"if(!showed)h='<div style=\"color:#aaa;font-style:italic;padding:10px\">нет событий</div>';"
"lst.innerHTML=h;"
"lst.scrollTop=lst.scrollHeight;"
"})['catch'](function(){"
"document.getElementById('log_list').innerHTML="
"'<div style=\"color:#e57373;padding:10px\">ошибка загрузки журнала</div>';});}"
"setInterval(pollLog,5000);"
"function pollStats(){"
"fetch('/api/stats')"
".then(function(r){return r.json();})"
".then(function(d){"
"var m=document.getElementById('stats_mod');"
"m.innerHTML='';"
"m.innerHTML+='<span>p1='+d.p1.toFixed(1)+'%</span>';"
"m.innerHTML+='<span>p10='+d.p10.toFixed(1)+'%</span>';"
"m.innerHTML+='<span>p25='+d.p25.toFixed(1)+'%</span>';"
"m.innerHTML+='<span>p50='+d.p50.toFixed(1)+'%</span>';"
"m.innerHTML+='<span>p75='+d.p75.toFixed(1)+'%</span>';"
"m.innerHTML+='<span>p90='+d.p90.toFixed(1)+'%</span>';"
"m.innerHTML+='<span>p99='+d.p99.toFixed(1)+'%</span>';"
"m.innerHTML+='<span style=\"font-size:.9em;color:#aaa\">n='+d.samples+' семплов</span>';"
"var c=document.getElementById('stats_cyc');"
"var ab=Math.floor(d.avg_burn/60),asb=Math.round(d.avg_burn%60);"
"var ap=Math.floor(d.avg_pause/60),asp=Math.round(d.avg_pause%60);"
"c.innerHTML='<div class=\"info-row\"><span class=\"info-label\">Циклов</span>'"
"+'<span class=\"info-val\">'+d.cycles+'</span></div>';"
"c.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Среднее время горения, мин:с</span>'"
"+'<span class=\"info-val\">'+ab+':'+(asb<10?'0':'')+asb+'</span></div>';"
"c.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Среднее время паузы, мин:с</span>'"
"+'<span class=\"info-val\">'+ap+':'+(asp<10?'0':'')+asp+'</span></div>';"
"c.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Моточасы</span>'"
"+'<span class=\"info-val\">'+d.burner_h.toFixed(1)+' ч</span></div>';"
"var g=document.getElementById('stats_gas');"
"g.innerHTML='<div class=\"info-row\"><span class=\"info-label\">Мгновенный расход</span>'"
"+'<span class=\"info-val\">'+d.instant_flow.toFixed(4)+' м&#179;/ч</span></div>';"
"g.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Накопленный объём</span>'"
"+'<span class=\"info-val\">'+d.integral_m3.toFixed(3)+' м&#179;</span></div>';"
"g.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Средний за 1 час</span>'"
"+'<span class=\"info-val\">'+d.avg_1h.toFixed(4)+' м&#179;/ч</span></div>';"
"g.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Средний за 3 часа</span>'"
"+'<span class=\"info-val\">'+d.avg_3h.toFixed(4)+' м&#179;/ч</span></div>';"
"g.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Средний за 12 часов</span>'"
"+'<span class=\"info-val\">'+d.avg_12h.toFixed(4)+' м&#179;/ч</span></div>';"
"g.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Средний за сутки</span>'"
"+'<span class=\"info-val\">'+d.avg_24h.toFixed(4)+' м&#179;/ч</span></div>';"
"g.innerHTML+='<div class=\"info-row\"><span class=\"info-label\">Средний за неделю</span>'"
"+'<span class=\"info-val\">'+d.avg_7d.toFixed(4)+' м&#179;/ч</span></div>';"
"if(d.gas_meter_base!=null&&!dirtyFields.mb){"
"document.getElementById('meter_base').value=d.gas_meter_base.toFixed(3);"
"document.getElementById('meter_total').textContent=d.gas_meter_total.toFixed(3);}"
"var cl=document.getElementById('corr_log');"
"if(d.corrections&&d.corrections.length>0){"
"var h='<table class=\"corr-table\"><tr><th>Время</th><th>Факт</th><th>Расчёт</th><th>&#916;</th><th>%</th><th>%/мес</th><th>K было</th><th>K стало</th></tr>';"
"for(var i=0;i<d.corrections.length;i++){"
"var e=d.corrections[i];"
"var dc=e.diff>=0?'corr-diff-pos':'corr-diff-neg';"
"var pctStr=e.pct.toFixed(1)+'%';"
"var pctm='--';"
"if(i>0){"
"var prev=d.corrections[i-1];"
"var days=(e.ts-prev.ts)/86400;"
"if(days>0.01)pctm=(Math.abs(e.pct)/days*30).toFixed(1)+'%';}"
"h+='<tr><td>'+e.t+'</td>'"
"+'<td class=\"corr-val\">'+e.ar.toFixed(3)+'</td>'"
"+'<td class=\"corr-val\">'+e.et.toFixed(3)+'</td>'"
"+'<td class=\"'+dc+'\">'+(e.diff>=0?'+':'')+e.diff.toFixed(3)+'</td>'"
"+'<td>'+pctStr+'</td>'"
"+'<td>'+pctm+'</td>'"
"+'<td>'+e.pk.toFixed(4)+'</td>'"
"+'<td class=\"corr-val\">'+e.nk.toFixed(4)+'</td></tr>';}"
"h+='</table>';"
"cl.innerHTML=h;}"
"else{cl.innerHTML='<div style=\"color:#555;font-style:italic;padding:8px\">нет коррекций</div>';}"
"})['catch'](function(){});}"
"setInterval(pollStats,10000);"
"switchTab('status');"
"</script>"
"</body></html>";
